#! /bin/sh

WHO=jecottrell3
WHERE=github.com
SSH=ssh://git@$WHERE
WEB=https://$WHERE
USR=https://$WHO@$WHERE

case $1 in
(-s)	PULL=$SSH PUSH=$SSH; shift;;
(-h)	PULL=$WEB PUSH=$WEB; shift;;
(-p)	PULL=$WEB PUSH=$USR; shift;;
(*)	echo "usage:	$0 -[shp]
	-s	SSH
	-h	HTTP
	-p	user@HTTP"; exit 1;;
esac

WHAT=${1:-._}

cd $RBJ
echo git remote -v
echo git remote -v set-url        origin $PULL/$WHO/$WHAT.git
echo : ==== :
echo git remote -v set-url --push origin $PUSH/$WHO/$WHAT.git
echo git remote -v
