#! /bin/sh -x

URL=git@github.com:jecottrell3/._.git

case $1 in
(-s)	                URL=git@github.com:jecottrell3/._.git;;
(-h)	URL=https://jecottrell3@github.com/jecottrell3/._.git;;
esac

cd $RBJ
git remote -v
git remote -v set-url origin $URL
git remote -v
