#! /usr/bin/perl

use strict;	# $Id: fixown 274 2013-12-05 01:30:57Z JECottrell3@gmail.com $
use integer;

$| = 1;
my $debug = 0;
my $exec  = 0;
my $waltz = 1;	# suppress
my $bimas = 1;	# suppress
my $noop  = 0;
my $gonly = 0;
# User UID/GID
my (%name, %ogid, %nuid);	# Indexed by Old UID
my $date;

chomp($date = `date`);
print ": BEGIN $date $0 @ARGV\n";	# signon
################################################################
#	Option Processing
################################################################

while ($ARGV[0] =~ m/^-/)
{
	++$debug if ($ARGV[0] eq '-d');
	++$exec  if ($ARGV[0] eq '-x');
	--$waltz if ($ARGV[0] eq '-w');
	--$bimas if ($ARGV[0] eq '-b');
	++$noop  if ($ARGV[0] eq '-n');
	++$gonly if ($ARGV[0] eq '-g');
	shift;
}

###############################################################
#	Build Transmat Table, indexed by Old UID
################################################################

my $count = 0;			# Account Count
while (<DATA>)
{
	my ($name, $uid, $gid, $nid, $flag) = split ' ';
	my $OK = 0;
	   $OK = 1 if ($noop);
	   $OK = 1 if ($flag eq 'CHANGE');
	   $OK = 1 if ($flag eq 'GROUP' && $gonly);
	next unless $OK;
	++$count;
	$ogid{$uid} = $gid;	# old GID
	$nuid{$uid} = $nid;	# new UID
	$name{$uid} = $name;	# old user name
	$name{$nid} = $name;	# new user name
}
close DATA;
$debug && print ": $count accounts\n";

################################################################
#	File Fixer
################################################################

my $total  = 0;
my $chown  = 0;
my $chgrp  = 0;

@ARGV && open ARGV, "find @ARGV -xdev -print0 |"; $/ = "\0";

while (<>)
{
	++$total;
	# exclusions
	next if ($waltz && m%^/export/./waltz2?/%);
	next if ($waltz && m%^/var/backup2?/%);
	next if ($waltz && m%^/export/./backup2?/%);
	next if (m%^/media/%);
	next if (m%^/misc/%);
	next if ($bimas && m%^/bimas%i);
	next if ($bimas && m%/readonly_bimas/%);
	next if ($bimas && m%^/usr[_/]local/bimas/%i);
	next if ($bimas && m%^/old_bimas_disks/%);

	chomp(my $path = $_);	# Old NL
	s/\0$//;		# New NL

	# File UID/GID
	my ($fuid, $fgid) = (lstat $path)[4, 5];
	my ($suid, $sgid) = (-1, -1);
	my $nuid;
	my $ogid;
	my $name;

	my $type = -l _ ? 'link' : -d _ ? 'dir' : 'file';

	if ($fuid >= 1000000)	# UID converted, GID maybe Evil
	{
		$nuid = $fuid;
		$ogid = -1;
	} else {		# Normal, unconverted
		$nuid = $nuid{$fuid}; next unless ($nuid);
		$ogid = $ogid{$fuid}; die  unless ($ogid);
	}

	$name = $name{$fuid} || 'NOUSER';

	# system call parms
	$suid = $nuid == $fuid ? -1 : $nuid;
	$suid = -1 if ($gonly);
	$sgid = $ogid != $fgid ? -1 : $nuid;

	# Evil GIDs
	$sgid = $nuid if $fgid == 99;
	$sgid = $nuid if $fgid == 199;
	$sgid = $nuid if $fgid == 60001;		# nobody
	$sgid = $nuid if $fgid == 32892;		# old hassan
	$sgid = $nuid if $fgid == 65534;		# 32 bit nobody
	$sgid = $nuid if $fgid == 4294967294;		# 64 bit nobody

	next if ($suid == -1 && $sgid == -1);		# no change
	next if ($ogid == $nuid);			# redundant
	
	my $carg  = $suid > 0 ?  "$suid" : '';		# command
	   $carg .= $sgid > 0 ? ":$sgid" : '';		#    line
	my $sarg  = sprintf "%d,%d,", $suid, $sgid;	# syscall

	# External CHOWN

	my $cmd = $noop ? ': own' : 'chown';

	$debug &&
	printf ":  $type\t %-24s'%s' # $name\n", "$fuid:$fgid", $path;
	printf      "%s -h %-24s'%s' # $name $fuid $fgid\n", $cmd, $carg, $path; 

	next     if($noop);
	next unless($exec);

	# Internal CHOWN

	++$chown if ($suid != -1);
	++$chgrp if ($sgid != -1);
	$type == 'link' ?
		system	'chown', '-h', $carg, $path :	# no lchown
			 chown($suid, $sgid,  $path);	# internal
}

chomp($date = `date`);
print ":  END  $date $0 chown: $chown chgrp: $chgrp total: $total.\n";	# signoff
exit;

################################################################
#		Account Data
################################################################

__END__
fpujvgef	21379		199		  1011990	PUNATR
yrrlf		32859		99		  1012059	PUNATR
yrrlf		1012059		32859		1012059		PUNATR
wepnfgba	30871		99		200058867	PUNATR
wgbzyva		1478		99		  1010891	PUNATR
lhnak4		200105305	99		200105305	PUNATR
lelnobi		32756		199		  1353007	PUNATR
lvatf		27952		99		  1081861	PUNATR
lbatfyrr	3183		99		  1012059	PUNATR
lnatl10		34210		99		  1443932	PUNATR
kvnbjra		31346		99		  1215942	PUNATR
kvnatm		30358		30358		  1162370	PUNATR
jonexre		33069		522		  1013557	PUNATR
jnatx3		34537		99		200055987	PUNATR
jnatu3		32075		99		  1258615	PUNATR
jnatt3		33811		100		  1436682	PUNATR
jnatny		27824		99		  1066192	PUNATR
ifnz		29751		99		  1150647	PUNATR
ibixb		33402		99		  1298484	PUNATR
gehfo		33101		99		  1015959	PUNATR
gubggh		32575		199		  1338269	PUNATR
gtzlref		2858		99		  1131300	PUNATR
gnyyrlr		1224489		99		  1224489	PUNATR
fhatvha		31911		100		  1219771	PUNATR
fgunqn		30903		522		  1143270	PUNATR
fgrvaonp	2286		99		  1015297	PUNATR
fgrvaonp	1015297		9000		  1015297	PUNATR
fznyyxz		200107939	99		200107939	PUNATR
fvapnaz		33977		99		  1434312	PUNATR
fubwnrvf	34825		99		200068628	PUNATR
furaf2		35427		99		  1434108	PUNATR
funuwvtn	31592		99		  1234695	PUNATR
fraguvytf	35131		547		200037274	PUNATR
frafrarlw	33401		100		  1301002	PUNATR
fronfgvnal	1438035		99		  1438035	PUNATR
fpbanag		30695		522		  1015468	PUNATR
fpuvagny	29291		99		  1144227	PUNATR
fnaqbe		1207		99		  1006652	PUNATR
fnyrz		1009402		99		  1009402	PUNATR
ehvqn		33395		100		  1147141	PUNATR
ebguzo		33887		199		  1438785	PUNATR
enivaqenan2	33547		99		  1429966	PUNATR
enfonaqj	34491		99		  1016744	PUNATR
enatrymt	33227		99		  1153683	PUNATR
envfn		9624		99		  1011319	PUNATR
dvhu2		33233		99		  1258554	PUNATR
chefyrl		18076		99		  1015619	PUNATR
cuhatgu		30003		99		  1056200	PUNATR
cnexwn2		34572		99		200056846	PUNATR
cnaqlna		33396		100		  1298481	PUNATR
cnwrivp		5905		99		  1009824	PUNATR
zhafba		1258		99		  1006155	PUNATR
zfgrryr		27374		99		  1004902	PUNATR
zbw2		200115232	99		200115232	PUNATR
zpdhrrac	9237		99		  1015451	PUNATR
zpzngg		14682		99		  1015120	PUNATR
zpperrql	28781		99		  1127027	PUNATR
znhqfyrlfg	35439		99		  1154068	PUNATR
znegvaoeb	35438		99		  1161914	PUNATR
ylaal		27109		99		  1019834	PUNATR
yhdhrq		500		99		200058862	PUNATR
yvm7		34429		99		200052018	PUNATR
yvhk8		34034		99		  1441445	PUNATR
yvhq2		33228		99		  1120817	PUNATR
yvbjw		28672		522		  1101006	PUNATR
yunzyva		33724		199		  1156294	PUNATR
ynhjvyy		32378		99		  1240113	PUNATR
xhbef		35441		99		200103333	PUNATR
xzrlre		2841		99		  1056953	PUNATR
xubxq		33744		100		  1434385	PUNATR
xrzcare		5338		99		  1006258	PUNATR
xpqo		34664		99		  1440313	PUNATR
xnxnerxn	70000		99		  1006354	PUNATR
wlgvna		33148		99		  1388891	PUNATR
wbfuvz2		33397		100		  1298482	PUNATR
wbuafba		1242		501		  1066755	PUNATR
wbuax		3588		99		  1040027	PUNATR
wbrunarfe	34473		99		  1441361	PUNATR
wznyyrl		3104		99		  1017343	PUNATR
wvc		1203		99		  1010904	PUNATR
wvc		1010904		1203		1010904		PUNATR
wvz3		33940		99		  1439786	PUNATR
vyo		20793		100		  1006013	PUNATR
uhnatw10	200118504	99		200118504	PUNATR
ubx		200115241	99		200115241	PUNATR
uvyycn		32547		99		  1065508	PUNATR
urlvjra		30986		99		  1195801	PUNATR
unffna		32892		32892		  1156786	PUNATR
undhrr		35132		547		  1416272	PUNATR
terraznaeo	32881		6002		  1366709	PUNATR
tbyqvaf         32629   	99      	  1330624	PUNATR
tynabjfxvfn	33463		100		  1420534	PUNATR
tynqqvate	31438		536		  1206885	PUNATR
troerzvpunryg	34573		99		  1352588	PUNATR
tnearewe	33008		100		  1350813	PUNATR
tnaqyre		4903		99		  1006013	PUNATR
senmvan		29314		99		  1145188	PUNATR
ratw		34617		99		  1368547	PUNATR
rnfnxv		27060		99		  1056077	PUNATR
qehff		27812		99		  1066191	PUNATR
qcbg		34186		99		  1222484	PUNATR
qbnag		31282		99		  1211802	PUNATR
qntqht		28374		99		  1107639	PUNATR
pblarz		32132		99		  1237789	PUNATR
pbggeryy	200115213	99		200115213	PUNATR
pbyyvrxe	33572		99		  1147859	PUNATR
purhatu		27871		99		  1072415	PUNATR
purau10		35437		99		200098983	PUNATR
puratf6		34864		99		200070852	PUNATR
punatq4		33692		100		  1432850	PUNATR
ohgpureft	35056		199		200080654	PUNATR
obeafgrvang	34365		99		200049842	PUNATR
orezrwbt	33889		199		  1376709	PUNATR
oneow		28197		99		  1106445	PUNATR
nevs		11916		199		  1052063	PUNATR
nevs		1052063		11916		1052063		PUNATR
