#! /usr/bin/python

from __future__ import print_function

import re
import sys

wids = [0] * 99
rows = []
fmt  = ''
spc  = ' '
fld  = '\s+'

# read lines, split, compute widths

if len(sys.argv) > 1: spc = fld = sys.argv[1]

for line in sys.stdin:
        line.rstrip()
        cols = re.split(fld, line)
        idx = 0
        for col in cols:
                wid = len(col)
####		if wid > 99: print('=%d=%s\n' % (wid, col))
                if    wids[idx] < wid:
                      wids[idx] = wid
                idx += 1
                
        rows.append(cols)

#print(wids)

# justify and print

for cols in rows:
#        print(cols)
        line = ''
        print(spc.join(
                        map(lambda t: t[0].ljust(t[1]),
                                zip(cols, wids))))
#### print(wids)
