#! /bin/sh

VG=${1:-$(hostname)}

loudly() { echo "$@"; eval "$@"; }

loudly pvcreate	/dev/sda4
loudly vgcreate $VG	/dev/sda4
loudly vgchange $VG -ay

for x in core base x11 dev srv kde gno win
do
	loudly lvcreate -L 10G -n $x $VG
	loudly mke2fs -jvL $x /dev/$VG/$x \> /dev/null
done
loudly lvcreate -L 2G -n swap $VG
loudly mkswap -L swap /dev/$VG/swap
