#! /bin/sh -x

cp /etc/hosts /repo/files

case $(hostname) in
(yoko)	: do nothing;;
(*)	scp 1.2.3.9:/etc/hosts /etc/hosts;;
esac

/root/bin/h2d && service dhcpd restart &&
/root/bin/h2n && rndc reload &&
: "[34;46mYOW! Are we having [31mNAMES[34m yet?[0m"
